// imports
import Head from "next/head";
import { BsFillMoonStarsFill } from "react-icons/bs";
import { AiOutlineTwitter, AiFillLinkedin, AiFillGithub } from "react-icons/ai";
import  VelocityScroll  from "./slider";
// images
import Image from "next/image";
import design from "../public/design.png";
import code from "../public/code.png";

import ashu from "../public/ashu.jpg";
import firebase from "../public/icons/firebase.png";
import git from "../public/icons/git.png"
import github from "../public/icons/github (1).png" 
import html5 from "../public/icons/html5.png"
import hugging from "../public/icons/hugging face.png" 
import javascript from "../public/icons/javascript.png"
import leetcode from "../public/icons/leetcode.png"
import midjourney from "../public/icons/midjourney.png"
import mongodb from "../public/icons/mongodb.png"
import node from "../public/icons/node-js.png"
import npm from "../public/icons/npm.png"
import react from "../public/icons/react.png"
import redux from "../public/icons/redux.png"
import sql from "../public/icons/sql-server.png"
import tailwind from "../public/icons/tailwind-css.png"
import typescript from "../public/icons/typescript.png"
import currency from "../public/projects/currency.png"
import hoobank from "../public/projects/hoobank.png"
import putuk from "../public/projects/putuk.png"
import codeclash from "../public/projects/codeclash.png"
import chrome from "../public/projects/chrome.png"
import Assess from "../public/projects/Assess.png"
import Auth from "../public/projects/Auth.png"
import logosign from "../public/Signature.png"
import mask from "../public/mask.svg"
// import { AnimatePresence } from "framer-motion";



// hooks
import { useState } from "react";
// import useMousePosition from "../utils/useMousePosition"


// applicaiton
export default function Home() {
  // functions
  // const {x,y} = useMousePosition();
  const [darkmode, setdarkmode] = useState(true);
  
  return (
    <div className={darkmode ? "dark" : ""}>
      <div className="absolute inset-0 -z-10 h-full w-full bg-white bg-[radial-gradient(#e5e7eb_1px,transparent_1px)] [background-size:16px_16px]"></div>
      <Head>
        <title>Ashutosh</title>
        <meta name="description" content="Generated by create next app" />
        <style>
          @import
          url('https://fonts.googleapis.com/css2?family=Poppins:wght@300;400;600;800&display=swap');
        </style>
        <link rel="icon" href="/AshuIcon.png" />
      </Head>
      

      
      
      <main className="font-poppins overflow-x-hidden bg-white px-6 md:px-20 lg:px-40 dark:bg-[#1D1D1D]">
        
        <section className="min-h-screen">
          <nav className="pt-10 mb-8 flex justify-between">
            <h1 className=" text-xl w-fit  dark:text-white">Ashutosh</h1>
            <ul className="flex items-center">
              <li>
                <BsFillMoonStarsFill
                  className=" cursor-pointer text-xl mx-5 dark:text-white"
                  onClick={() => setdarkmode(!darkmode)}
                />
              </li>
              <li>
                <a
                  href="https://drive.google.com/file/d/1mMll14ia0-oJ7_61Ir1VEf1c9gTszNR6/view?usp=sharing"
                  target="_blank"
                  className=" bg-purple-600 text-white px-4 py-2 boder-none rounded-md "
                >
                  Resume
                </a>
              </li>
            </ul>
          </nav>

          {/* hero */}
          <div className="text-center p-10 ">

            <h2 className="text-4xl m-0.5 sm:text-5xl mx-auto font-AVD font-bold text-[#ccbaa9] md:text-6xl lg:text-7xl ">
              Ashutosh Gupta
            </h2>
            <h3 className="text-2xl py-4 md:text-3xl dark:text-white">
              Full Stack Web Developer
            </h3>
            </div>
            {/* profile image */}
          
            <div
            className="mx-auto
           relative bg-gradient-to-black from-purple-200 min-w-40 sm:w-80
            h-80 mt-8 sm:p-5 rounded-full">
            <div className="absolute inline-flex flex-shrink cursor-pointer z-10 inset-0 bg-gradient-to-t from-[#1D1D1D] to-transparent"></div>

            <Image src={ashu} alt="profile" className="absolute inline-flex flex-shrink inset-0 h-full w-full object-cover"/>
          </div>


            <div className="relative flex justify-center items-center text-center p-4 mt-4 sm:p-10 ">

            <p className=" text-xl mt-10 sm:py-2 text-gray-400 text-left sm:text-center sm:leading-10 max-w-3xl mx-auto">
            In the world of web development, 
            I've honed my skills to deliver high-quality digital 
            experiences. While I specialize in frontend and backend 
            technologies, I also embrace a generalist mindset, constantly 
            learning and adapting. My goal is simple: <span>perfection</span>, <span>finesse</span> and <span>impact</span>
            </p>
            

         
          </div>
          
          {/* social media */}
          <div className="text-5xl py-4 flex flex-row justify-start sm:justify-center gap-4 sm:gap-16 text-gray-600">
            <a href="https://github.com/TheAshutoshGupta"><AiFillGithub className="hover:text-white hover:scale-105 duration-200" /></a>
            <a href="https://www.linkedin.com/in/ashutooshgupta/"><AiFillLinkedin  className="hover:text-white hover:scale-105 duration-200"/></a>
            <a href="https://twitter.com/TheAshutshgupta"><AiOutlineTwitter  className="hover:text-white hover:scale-105 duration-200"/></a>
          </div>

        </section>
        {/* Added Section */}
        <div className="my-8">
        <VelocityScroll/> </div>
        

        <section>
          <div>
            <h3 className=" text-3xl py-10 font-bold opacity-60 dark:text-white dark:opacity-100">
              Skills
            </h3>
            <div className=" flex flex-wrap justify-center items-center flex-row gap-5 py-2 text-gray-400 leading-6">
            <Image src={firebase} alt="img" className={` w-10 h-10`}/>
            <Image src={git} alt="img" className={` w-10 h-10`}/>
            <Image src={github} alt="img" className={`${darkmode?"invert":""} w-10 h-10`}/>
            <Image src={html5} alt="img" className={` w-10 h-10`}/>
            <Image src={hugging} alt="img" className={`w-10 h-10`}/>
            <Image src={javascript} alt="img" className={` w-10 h-10`}/>
            <Image src={leetcode} alt="img" className={` w-10 h-10`}/>
            <Image src={midjourney} alt="img" className={` w-10 h-10`}/>
            <Image src={mongodb} alt="img" className={` w-10 h-10`}/>
            <Image src={node} alt="img" className={` w-10 h-10`}/>
            <Image src={npm} alt="img" className={` w-10 h-10`}/>
            <Image src={react} alt="img" className={`$ w-10 h-10`}/>
            <Image src={redux} alt="img" className={` w-10 h-10`}/>
            <Image src={sql} alt="img" className={`${darkmode?"invert":""} w-10 h-10`}/>
            <Image src={tailwind} alt="img" className={`${darkmode?"invert":""} w-10 h-10`}/>
            <Image src={typescript} alt="img" className={` w-10 h-10`}/>
            </div>
          </div>
          </section>
        {/* section 2 */}

        <section>
          <div>
            <h3 className=" text-3xl pb-6 pt-10  font-bold opacity-60 dark:text-white dark:opacity-100">
              Through Out 
            </h3>
            {/* <p className=" text-sm py-2 text-gray-400 leading-6">
              Lorem ipsum dolor sit amet consectetur adipisicing elit. Itaque
              distinctio nihil fugiat ea perferendis qui nulla facere
              consequatur dolor sit amet consectetur adipisicing elit. Itaque
              distinctio nihil perferendis qui nulla facere consequatur dolor
              sit amet consectetur adipisicing elit. Itaque distinctio nihil
            </p> */}
          </div>
          <div className="md:flex lg:flex gap-10 mx-auto">
            <div className="text-center md:w-1/2 shadow-lg p-5 rounded-xl my-10 dark:bg-gradient-to-b from-purple-600 ">
              <Image
                src={design}
                width={100}
                height={100}
                alt="design"
                className=" inline py-5"
              />
              <h3 className="text-2xl font-bold dark:text-white ">
                Education
              </h3>
               <p className=" text-sm py-2 flex flex-col dark:text-gray-300 text-gray-600 leading-6">
               <span>Persuing Btech in CS</span>
                <span>Been an Science Student</span>
               
              </p>
              
              {/*
              <h4 className="py-4 text-purple-600 text-md font-semibold">
                Design tools I use
              </h4> */}
              
              <p className="px-5 py-3 flex gap-2 text-left dark:text-gray-300 text-gray-600  text-sm"><span className="flex flex-col"
 >GL Bajaj Institute of Technology and Management : 2021 - 2025<span className="font-semibold dark:text-gray-300 text-gray-600">8.02 CGPA</span>
 {/* <span className="font-semibold dark:text-gray-300 text-gray-600">12th : 86.2%</span> */}
 </span></p>
 <p className="px-5 py-3 flex gap-2 text-left dark:text-gray-300 text-gray-600  text-sm"><span className="flex flex-col"
 >Udaya Public School: 2018 - 2020<span className="font-semibold dark:text-gray-300 text-gray-600">10th : 89.6%</span>
 <span className="font-semibold dark:text-gray-300 text-gray-600">12th : 86.2%</span>
 </span></p>
              
              
            </div>

            {/*  */}
            <div className="text-center md:w-1/2 shadow-lg p-5 rounded-xl my-10 dark:bg-gradient-to-b from-purple-600">
              <Image
                src={code}
                width={100}
                height={100}
                alt="design"
                className=" inline py-5"
              />
               <h3 className="text-2xl font-bold dark:text-white">
                Side Hustles
              </h3>
              
              <p className=" text-sm py-2 dark:text-gray-300 text-gray-600 flex flex-col leading-6">
                
                <span>Been an Graphic Designer</span>
                <span>Now a Full Stack Web Developer</span>
              </p>
      
            
              <p className="px-5 py-3 flex gap-2 text-left dark:text-gray-300 text-gray-600  text-sm"><span className="flex flex-col"
 >Freelance Graphic Designer : 2020-2021 <span className="font-semibold dark:text-gray-300 text-gray-600">Raised 70 K</span>
 </span></p>
 <p className="px-5 py-3 flex gap-2 text-left dark:text-gray-300 text-gray-600  text-sm"><span className="flex flex-col"
 >Learning Web Development : 2023-2024  <span className="font-semibold dark:text-gray-300 text-gray-600">created 20+ Websites</span>
 </span></p>
              
            </div>
          
          </div>
        </section>

        {/* last section */}
        <section>
          <div>
            <h3 className=" text-3xl py-5 font-bold opacity-60 dark:text-white dark:opacity-100">
              Portfolio
            </h3>
            {/* <p className=" text-sm py-5 text-gray-400 leading-6">
              
            </p> */}
          </div>
          {/* images */}
          <div className="flex flex-col mt-4 gap-10 lg:flex-row lg:flex-wrap">
            
          <a href="https://course-assessment-ai-sksx.vercel.app/" className=" relative basis-1/3 flex-1 cursor-pointer hover:scale-105 duration-200">
              <Image
                src={Assess}
                alt="Assess"
                className="rounded-lg object-contain w-full h-full m:w-[220px] md:h-[400px]"
                layout="responsive"
              />
            </a>
          <a href="https://authre.vercel.app/" className=" relative basis-1/3 flex-1 cursor-pointer hover:scale-105 duration-200">
              <Image
                src={Auth}
                alt="Auth"
                className="rounded-lg object-contain w-full h-full m:w-[220px] md:h-[400px]"
                layout="responsive"
              />
            </a>
          <a href="https://chromewebstore.google.com/detail/prioritize/fdfpeopajimflfgmpkjbjdmfpofgikih" className=" relative basis-1/3 flex-1 cursor-pointer hover:scale-105 duration-200">
              <Image
                src={chrome}
                alt="chrome"
                className="rounded-lg object-contain w-full h-full m:w-[220px] md:h-[400px]"
                layout="responsive"
              />
            </a>
            
            <a href="https://travelapptheashutoshgupta.vercel.app/" className="basis-1/3 flex-1  cursor-pointer hover:scale-105 duration-200">
              <Image
                src={putuk}
                alt="putuk"
                className="rounded-lg object-cover w-full h-full m:w-[220px] md:h-[400px]"
                layout="responsive"
              />
            </a>
            <a href="https://hoobanktheashutoshgupta.vercel.app/" className="basis-1/3 flex-1  cursor-pointer hover:scale-105 duration-200">
              <Image
                src={hoobank}
                alt="hoobank"
                className="rounded-lg object-cover w-full h-full m:w-[220px] md:h-[400px]"
                layout="responsive"
              />
            </a>
            <a href="https://currencyconvertortheashutoshgupta.vercel.app/" className="basis-1/3 flex-1  cursor-pointer hover:scale-105 duration-200">
              <Image
                src={currency}
                alt="currency"
                className="rounded-lg object-cover w-full h-full m:w-[220px] md:h-[400px]"
                layout="responsive"
              />
            </a>
            
          </div>
        </section>
        <section>
          <div>
            <h3 className=" text-3xl py-10 font-bold opacity-60 dark:text-white dark:opacity-100">
              
            </h3>
            <div className=" flex flex-wrap justify-center md:justify-between items-center flex-row gap-5 py-2 text-gray-400 leading-6">
              <div className="flex gap-2 mx-auto dark:text-gray-300 ">All copyrights reserved to : Ashutosh</div>
              
              </div>
            </div>
          
          </section>
      </main>
    </div>
  );
}
